# Answer 1

Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list, while array_list is a NumPy array.

You can print the data types of both variables using the type function in Python:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


# Answer 2

To print the data type of each and every element of both variables list_ and array_list, you can use a loop to iterate over the elements and use the type function to print their data types. Here is an example code:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in the list
for element in list_:
    print(type(element))

# Print data types of each element in the NumPy array
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Answer 3

Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list after the change array_list = np.array(object=list_, dtype=int).

Before the change, the elements in list_ were strings (str data type), while after the change, the elements in array_list are integers (int data type).

Here is an example code to print the data types of each and every element present in both list_ and array_list:

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in the original list
for element in list_:
    print(type(element))

# Print data types of each element in the NumPy array
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


As you can see, the data type of each element in the original list is str, while the data type of each element in the NumPy array is numpy.int64.

Regarding the code provided in the second part of the question, num_list is a nested list containing integers, and num_array is a NumPy array created from this list using the np.array() function. The elements in num_array will have the data type int64 (assuming the default data type for integers is used).

# Answer 4

To find the shape and size of a NumPy array, you can use the shape and size attributes of the array, respectively. Here is an example code to find these characteristics of the num_array variable:

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of the array
print(num_array.shape)

# Find the size of the array
print(num_array.size)

(2, 3)
6


# Answer 5

You can create a NumPy array of a 3x3 matrix containing zeros only using the np.zeros() function. The np.zeros() function takes a shape tuple as its argument, which specifies the size of the array in each dimension. Here is an example code to create the array:

In [6]:
import numpy as np

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Answer 6

You can create an identity matrix of shape (5, 5) using the np.identity() function. The np.identity() function takes a single argument, which specifies the size of the matrix (i.e., the number of rows/columns), and returns an identity matrix of that size.

In [7]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
