#### Q1) What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow uses a variety of data structures to represent and manipulate data. The most basic data structure is the tensor. A tensor is a multidimensional array of data. Tensors can be used to represent images, text, audio, and other types of data.

Other data structures used in TensorFlow include:

Constants are tensors that have a fixed value. Constants are often used to represent the input data to a TensorFlow model.
Variables are tensors that can be updated during training. Variables are often used to represent the weights and biases of a neural network.
Datasets are collections of tensors that are used to represent training data or test data. Datasets can be used to load data into TensorFlow and to iterate over data during training.
Here are some examples of TensorFlow data structures:

A tensor representing an image could have the shape (28, 28, 1), which means that it is a 28x28x1-dimensional array of data.
A tensor representing a text string could have the shape (1, 100), which means that it is a 1x100-dimensional array of data.
A tensor representing a variable could have the shape (10, 10), which means that it is a 10x10-dimensional array of data that can be updated during training.


#### Answer 2)

In TensorFlow, a constant is a type of tensor whose value cannot be changed once it is defined. It is typically used to store fixed values that are known and constant throughout the execution of a graph. On the other hand, a variable is a type of tensor that holds mutable values and can be modified during the execution of a graph. Variables are often used to store and update the parameters of a model during training.

Here's an example to illustrate the difference between a TensorFlow constant and a TensorFlow variable:

In [1]:
import tensorflow as tf

# TensorFlow Constant
a = tf.constant(5.0)
b = tf.constant(3.0)
c = a + b

# TensorFlow Variable
x = tf.Variable(2.0)
y = tf.Variable(1.0)
z = x * y

# Print the values of the constants and variables
print("Constant c:", c)
print("Variable z:", z)

Constant c: tf.Tensor(8.0, shape=(), dtype=float32)
Variable z: tf.Tensor(2.0, shape=(), dtype=float32)


In [2]:
import tensorflow as tf

# Matrix Multiplication
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(a, b)

print("Matrix Multiplication Result:")
print(result)


Matrix Multiplication Result:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [3]:
import tensorflow as tf

# Element-wise Operations
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
add_result = tf.add(a, b)
mul_result = tf.multiply(a, b)

print("Element-wise Addition Result:")
print(add_result)
print("Element-wise Multiplication Result:")
print(mul_result)


Element-wise Addition Result:
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Element-wise Multiplication Result:
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


## Practical Implementation

### Task 1: Creating and manipulating Matrices


1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random _normal function. Display the values of matrix A.
2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated _normal function. Display the values of matrix B.
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [7]:
import tensorflow as tf

# Create matrix A with dimensions 3x3
matrix_A = tf.random.normal(shape=(3, 3))

# Display the values of matrix A
print("Matrix A:")
print(matrix_A.numpy())


Matrix A:
[[-2.3706174  -0.8929709  -0.49022278]
 [ 0.16878602  0.33538055 -0.18142405]
 [ 0.63322645  0.7539289   0.44529152]]


In [8]:
import tensorflow as tf

# Create matrix B with dimensions 4x4
matrix_B = tf.random.truncated_normal(shape=(4, 4))

# Display the values of matrix B
print("Matrix B:")
print(matrix_B.numpy())


Matrix B:
[[ 1.1985513  -0.77889365  0.9087815  -0.7863372 ]
 [-1.0621189  -0.27241224  0.666117    0.48272175]
 [ 1.4852724   1.6693741  -1.2516122  -1.08297   ]
 [-0.23293084 -0.20296349 -0.02291392 -0.49958625]]


In [9]:
import tensorflow as tf

# Create matrix C with dimensions 2x2
mean = 3
stddev = 0.5
matrix_C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Display the values of matrix C
print("Matrix C:")
print(matrix_C.numpy())


Matrix C:
[[2.7023098 2.9189312]
 [3.945863  2.4548788]]


In [10]:
import tensorflow as tf

# Create matrix A
matrix_A = tf.random.normal(shape=(3, 3))

# Create matrix B
matrix_B = tf.random.normal(shape=(3, 3))

# Perform matrix addition between matrix A and matrix B
matrix_D = tf.add(matrix_A, matrix_B)

# Display the values of matrix D
print("Matrix D (A + B):")
print(matrix_D.numpy())


Matrix D (A + B):
[[ 1.1981889  -1.0744995   1.2272512 ]
 [ 1.6528794   0.22312078  1.8299372 ]
 [-0.41684222 -1.0419228  -0.08077431]]


In [11]:
import tensorflow as tf

# Create matrix C
matrix_C = tf.random.normal(shape=(2, 2))

# Create matrix D
matrix_D = tf.random.normal(shape=(2, 2))

# Perform matrix multiplication between matrix C and matrix D
matrix_E = tf.matmul(matrix_C, matrix_D)

# Display the values of matrix E
print("Matrix E (C * D):")
print(matrix_E.numpy())


Matrix E (C * D):
[[-0.7070457 -0.7812091]
 [-3.1789455 -3.412626 ]]
